version: 2.1

orbs:
  singularity: singularity/singularity@1.0.10


################################################################################
# Workflows
################################################################################

workflows:
  version: 2
  test:
    jobs:
      - run-scompose-ci-tests: &base_job
          filters:
            branches:
              ignore: master
          name: "Latest Singularity with Python 3"
          python: 3
          singularity: 3.5.1

################################################################################
# Functions
################################################################################

install_scompose: &install_scompose
  name: Install Singularity Compose
  command: |
        cd ~/repo
        pip install .[all]

test_scompose: &test_scompose
  name: Test Singularity Compose
  command: |
        cd ~/repo
        pip install .[all]
        pytest -sv scompose/tests/test_depends_on.py
        pytest -sv scompose/tests/test_client.py
        pytest -sv scompose/tests/test_utils.py

commands:
  install_dependencies:
    parameters:
      python:
        type: integer
        description: "Python version: 2 or 3"
    steps:
      - run: |
          PYTHON_VERSION="<< parameters.python >>"
          CONDA_PATH="$HOME/conda/Python${PYTHON_VERSION}"
          echo 'export PATH="'"$CONDA_PATH"'/bin:$PATH"' >> "$BASH_ENV"
          source "$BASH_ENV"
          if [ ! -d "$CONDA_PATH" ]; then
              CONDA_SCRIPT=Miniconda${PYTHON_VERSION}-latest-Linux-x86_64.sh
              wget https://repo.anaconda.com/miniconda/$CONDA_SCRIPT
              /bin/bash $CONDA_SCRIPT -b -p $CONDA_PATH
          else
              echo "Miniconda is already installed, continuing to build."
          fi
          python --version
          [ $(python -c'import sys;print(sys.version_info.major)') -eq $PYTHON_VERSION ]

          pip install --upgrade pytest setuptools

################################################################################
# Jobs
################################################################################

jobs:
  run-scompose-ci-tests:
    parameters:
        python:
          type: integer
          description: "Python version: 2 or 3"
          default: 3
        singularity:
          type: string
          description: "Singularity version"
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys: v2-dependencies
      - install_dependencies:
          python: << parameters.python >>
      - singularity/install_debian_3:
          go-version: "1.13"
          singularity-version: << parameters.singularity >>
      - save_cache:
          paths:
            - ~/conda
          key: v2-dependencies
      - run: *install_scompose
      - run: *test_scompose
