version: 2.1

# https://circleci.com/orbs/registry/orb/singularity/singularity
# defaults to golang 1.13 and singularity 3.5.0
orbs:
  singularity: singularity/singularity@1.0.10


################################################################################
# Workflows
################################################################################

workflows:
  version: 2
  test:
    jobs:
      - run-scompose-ci-tests:
          filters:
            branches:
              ignore: master

################################################################################
# Functions
################################################################################

install_scompose: &install_scompose
  name: Install Singularity Compose
  command: |
        cd ~/repo
        pip install .[all]

test_scompose: &test_scompose
  name: Test Singularity Compose
  command: |
        cd ~/repo
        pip install .[all]
        pytest -sv scompose/tests/test_depends_on.py
        pytest -sv scompose/tests/test_client.py
        pytest -sv scompose/tests/test_utils.py

install_dependencies: &install_dependencies
  name: Install Python dependencies
  command: |
        PYTHON_VERSION=3
        CONDA_PATH="$HOME/conda/Python${PYTHON_VERSION}"
        echo 'export PATH="'"$CONDA_PATH"'/bin:$PATH"' >> "$BASH_ENV"
        source "$BASH_ENV"
        if [ ! -d "$CONDA_PATH" ]; then
            CONDA_SCRIPT=Miniconda${PYTHON_VERSION}-latest-Linux-x86_64.sh
            wget https://repo.anaconda.com/miniconda/$CONDA_SCRIPT
            /bin/bash $CONDA_SCRIPT -b -p $CONDA_PATH
        else
            echo "Miniconda is already installed, continuing to build."
        fi
        python --version
        [ $(python -c'import sys;print(sys.version_info.major)') -eq $PYTHON_VERSION ]
        pip install --upgrade pytest setuptools


################################################################################
# Jobs
################################################################################

jobs:
  run-scompose-ci-tests:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys: v3-dependencies
      - run: *install_dependencies
      - singularity/install-go
      - singularity/debian-install-3
      - save_cache:
          paths:
            - ~/conda
          key: v3-dependencies
      - run: *install_scompose
      - run: *test_scompose
